E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("B,Baibj->bjai", extract_mat(h_p, "AV", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("B,Bbjai->bjai", extract_mat(h_p, "AV", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("Bkk,Baibj->bjai", extract_mat(g_p, "AVoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("Bkk,Bbjai->bjai", extract_mat(g_p, "AVoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("Bki,Bakbj->bjai", extract_mat(g_p, "AVoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("Bki,Bbjak->bjai", extract_mat(g_p, "AVoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("Bkj,Baibk->bjai", extract_mat(g_p, "AVoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("Bkj,Bbkai->bjai", extract_mat(g_p, "AVoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bac,Bcibj->bjai", extract_mat(g_p, "AVvv", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bac,Bbjci->bjai", extract_mat(g_p, "AVvv", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bbc,Bcjai->bjai", extract_mat(g_p, "AVvv", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bbc,Baicj->bjai", extract_mat(g_p, "AVvv", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("Bkc,aibj,Bck->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("Bkc,Bckai,bj->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "AIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("Bkc,Bckbj,ai->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "AIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bkc,Bciak,bj->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "AIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bkc,Bcjbk,ai->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "AIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bkc,Bakci,bj->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "AIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("Bkc,Baick,bj->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "AIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bkc,Bbkcj,ai->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "AIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("Bkc,Bbjck,ai->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "AIvo", o, v), optimize="optimal");