E = E .+  +0.25000000  * fixed_einsum("Bai,aibj,Bbj->", extract_mat(g_p, "IVvo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("Bai,bjai,Bbj->", extract_mat(g_p, "IVvo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("ai,Baibj,Bbj->", extract_mat(g_p, "IAvo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("ai,Bbjai,Bbj->", extract_mat(g_p, "IAvo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("ab,aicj,bicj->", extract_mat(g_p, "IIvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("ij,ajbk,aibk->", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("ab,ciaj,bjci->", extract_mat(g_p, "IIvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("ij,akbj,akbi->", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("B,aibj,Baibj->", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * extract_mat(h_p, "IA", o, v) * fixed_einsum("Baibj,Baibj->", extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("Bii,ajbk,Bajbk->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("Bab,aicj,Bbicj->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("Bij,ajbk,Baibk->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("Bab,ciaj,Bbjci->", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("Bij,akbj,Bakbi->", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  +0.50000000  * fixed_einsum("ii,Bajbk,Bajbk->", extract_mat(g_p, "IAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("Bab,Baicj,bicj->", extract_mat(g_p, "VAvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("Bij,Bajbk,aibk->", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("Bab,Bciaj,bjci->", extract_mat(g_p, "VAvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("Bij,Bakbj,akbi->", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("Bia,bjck,Baj,bick->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("Bia,bjck,Bak,bjci->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("Bia,bjck,Bbi,ajck->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  -0.25000000  * fixed_einsum("Bia,bjck,Bci,akbj->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("Bia,bjck,Bbj,aick->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("Bia,bjck,Bck,aibj->", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("ia,Bbjck,Bbj,aick->", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E = E .+  +0.25000000  * fixed_einsum("ia,Bbjck,Bck,aibj->", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
