E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ba,Abicj,Acj->ai", extract_mat(g_p, "IIvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ba,Acjbi,Acj->ai", extract_mat(g_p, "IIvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ij,Abkaj,Abk->ai", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ij,Aajbk,Abk->ai", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ja,Abkci,Abkcj->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ja,Abick,Abjck->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ib,Acjak,Abkcj->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ib,Aajck,Abjck->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bjka,Abjci,Ack->ai", extract_mat(g, "voov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bcda,Abjdi,Acj->ai", extract_mat(g, "vvvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bcda,Adibj,Acj->ai", extract_mat(g, "vvvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jkba,Abick,Acj->ai", extract_mat(g, "oovv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jkba,Ackbi,Acj->ai", extract_mat(g, "oovv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bjka,Acibj,Ack->ai", extract_mat(g, "voov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bjic,Abjak,Ack->ai", extract_mat(g, "voov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcij,Abkaj,Ack->ai", extract_mat(g, "vvoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkil,Abkal,Abj->ai", extract_mat(g, "oooo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcij,Aajbk,Ack->ai", extract_mat(g, "vvoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkil,Aalbk,Abj->ai", extract_mat(g, "oooo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bjic,Aakbj,Ack->ai", extract_mat(g, "voov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ABba,Abicj,Bcj->ai", extract_mat(g_p, "VVvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ABba,Acjbi,Bcj->ai", extract_mat(g_p, "VVvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ABij,Abkaj,Bbk->ai", extract_mat(g_p, "VVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ABij,Aajbk,Bbk->ai", extract_mat(g_p, "VVoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("ia,Abjck,Abjck->ai", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Aja,Abkci,bkcj->ai", extract_mat(g_p, "VIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Aja,Abick,bjck->ai", extract_mat(g_p, "VIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Aib,Acjak,bkcj->ai", extract_mat(g_p, "VIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Aib,Aajck,bjck->ai", extract_mat(g_p, "VIov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbca,Acidk,Abjdk->ai", extract_mat(L, "ovvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbca,Adkci,Abjdk->ai", extract_mat(L, "ovvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbik,Aclak,Abjcl->ai", extract_mat(L, "ovoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbik,Aakcl,Abjcl->ai", extract_mat(L, "ovoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bcia,Abjdk,Acjdk->ai", extract_mat(L, "vvov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jkia,Abkcl,Abjcl->ai", extract_mat(L, "ooov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bcia,Adjbk,Ackdj->ai", extract_mat(L, "vvov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jkia,Ablck,Ablcj->ai", extract_mat(L, "ooov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcja,Abkdi,Ackdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbca,Acidk,Abkdj->ai", extract_mat(g, "ovvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkla,Abkci,Abjcl->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbca,Adkci,Abkdj->ai", extract_mat(g, "ovvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcja,Adibk,Ackdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkla,Abick,Ablcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcid,Abjak,Acjdk->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkib,Ackal,Ablcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbik,Aclak,Ablcj->ai", extract_mat(g, "ovoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbik,Aakcl,Ablcj->ai", extract_mat(g, "ovoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcid,Aajbk,Ackdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkib,Aalck,Ablcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");

E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ABja,Abkci,Bbkcj->ai", extract_mat(g_p, "VVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ABja,Abick,Bbjck->ai", extract_mat(g_p, "VVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ABib,Acjak,Bbkcj->ai", extract_mat(g_p, "VVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ABib,Aajck,Bbjck->ai", extract_mat(g_p, "VVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.50000000  * fixed_einsum("ABia,Abjck,Bbjck->ai", extract_mat(g_p, "VVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");

E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Aja,Bbkci,Acj,Bbk->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Aja,Bbick,Abj,Bck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Aib,Bcjak,Abk,Bcj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Aib,Bajck,Abj,Bck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Aia,Bbjck,Abj,Bck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Aia,Bbjck,Ack,Bbj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");

E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbka,Acldi,Abj,cldk->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbka,Acidl,Abj,ckdl->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbic,Adkal,Abj,cldk->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbic,Aakdl,Abj,ckdl->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbia,Ackdl,Abk,cjdl->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbia,Ackdl,Abl,ckdj->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbia,Ackdl,Acj,bkdl->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbia,Ackdl,Adj,blck->ai", extract_mat(L, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbka,Acldi,Abl,cjdk->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbka,Acldi,Acj,bldk->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbka,Acldi,Adj,bkcl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbka,Acidl,Abl,ckdj->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbka,Acidl,Acj,bkdl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbka,Acidl,Adj,blck->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbic,Adkal,Abk,cldj->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbic,Adkal,Abl,cjdk->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbic,Adkal,Adj,bkcl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbic,Aakdl,Abk,cjdl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbic,Aakdl,Abl,ckdj->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbic,Aakdl,Adj,blck->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");

E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbka,Acldi,Adk,bjcl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbka,Acidl,Ack,bjdl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbic,Adkal,Acl,bjdk->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbic,Aakdl,Ack,bjdl->ai", extract_mat(g, "ovov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
