E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bj,bjai->ai", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bj,aibj->ai", extract_mat(g_p, "IIvo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bjca,bjci->ai", extract_mat(g, "vovv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bjca,cibj->ai", extract_mat(g, "vovv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bjik,bjak->ai", extract_mat(g, "vooo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bjik,akbj->ai", extract_mat(g, "vooo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bbj,Bbjai->ai", extract_mat(g_p, "VAvo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bbj,Baibj->ai", extract_mat(g_p, "VAvo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("B,bjai,Bbj->ai", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("B,aibj,Bbj->ai", extract_mat(h_p, "IV", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * extract_mat(h_p, "IA", o, v) * fixed_einsum("Bbjai,Bbj->ai", extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * extract_mat(h_p, "IA", o, v) * fixed_einsum("Baibj,Bbj->ai", extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ja,bkci,bkcj->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ja,bick,bjck->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ib,cjak,bkcj->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ib,ajck,bjck->ai", extract_mat(F, "ov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Bjj,bkai,Bbk->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Bjj,aibk,Bbk->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bbc,bjai,Bcj->ai", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bjk,bkai,Bbj->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bbc,aibj,Bcj->ai", extract_mat(g_p, "IVvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bjk,aibk,Bbj->ai", extract_mat(g_p, "IVoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jj,Bbkai,Bbk->ai", extract_mat(g_p, "IAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("jj,Baibk,Bbk->ai", extract_mat(g_p, "IAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ba,Bbicj,Bcj->ai", extract_mat(g_p, "IAvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("ba,Bcjbi,Bcj->ai", extract_mat(g_p, "IAvv", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ij,Bbkaj,Bbk->ai", extract_mat(g_p, "IAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("ij,Bajbk,Bbk->ai", extract_mat(g_p, "IAoo", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jb,ckai,bjck->ai", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jb,aick,bjck->ai", extract_mat(g_p, "IIov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bcia,bjdk,cjdk->ai", extract_mat(L, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jkia,bkcl,bjcl->ai", extract_mat(L, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("bcia,djbk,ckdj->ai", extract_mat(L, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jkia,blck,blcj->ai", extract_mat(L, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcja,bkdi,ckdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcja,bidk,cjdk->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkla,bkci,bjcl->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcja,dkbi,cjdk->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcja,dibk,ckdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkla,bick,blcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcid,bjak,cjdk->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkib,ckal,blcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkib,clak,bjcl->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkib,akcl,bjcl->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("bcid,ajbk,ckdj->ai", extract_mat(g, "vvov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jkib,alck,blcj->ai", extract_mat(g, "ooov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbca,cidk,bjdk->ai", extract_mat(g, "ovvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("jbca,dkci,bjdk->ai", extract_mat(g, "ovvv", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbik,clak,bjcl->ai", extract_mat(g, "ovoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("jbik,akcl,bjcl->ai", extract_mat(g, "ovoo", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Bjb,ckai,Bbjck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bjb,ckai,Bbkcj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("Bjb,aick,Bbjck->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bjb,aick,Bbkcj->ai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.50000000  * fixed_einsum("ia,Bbjck,Bbjck->ai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s2, "VIvovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bja,Bbkci,bkcj->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bja,Bbick,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bib,Bcjak,bkcj->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +0.25000000  * fixed_einsum("Bib,Bajck,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bjb,Bckai,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -0.25000000  * fixed_einsum("Bjb,Baick,bjck->ai", extract_mat(g_p, "VAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
