E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * extract_mat(h_p, "II", o, v) * fixed_einsum("aibj->bjai", extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] +=  -0.25000000  * extract_mat(h_p, "II", o, v) * extract_mat(p2, "AIvovo", o, v);
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("ca,cibj->bjai", extract_mat(F, "vv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("ca,bjci->bjai", extract_mat(F, "vv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("cb,cjai->bjai", extract_mat(F, "vv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("cb,aicj->bjai", extract_mat(F, "vv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ik,akbj->bjai", extract_mat(F, "oo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ik,bjak->bjai", extract_mat(F, "oo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("jk,aibk->bjai", extract_mat(F, "oo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("jk,bkai->bjai", extract_mat(F, "oo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("kk,aibj->bjai", extract_mat(g_p, "IIoo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * extract_mat(p2, "AIvovo", o, v) * fixed_einsum("kk->", extract_mat(g_p, "IIoo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("B,Baibj->bjai", extract_mat(h_p, "VA", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("B,Bbjai->bjai", extract_mat(h_p, "VA", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("ckia,ckbj->bjai", extract_mat(L, "voov", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("ckia,bjck->bjai", extract_mat(L, "voov", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("ckjb,ckai->bjai", extract_mat(L, "voov", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("ckjb,aick->bjai", extract_mat(L, "voov", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ckib,ckaj->bjai", extract_mat(g, "voov", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ckib,ajck->bjai", extract_mat(g, "voov", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ckja,ckbi->bjai", extract_mat(g, "voov", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ckja,bick->bjai", extract_mat(g, "voov", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("cadb,cidj->bjai", extract_mat(g, "vvvv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("cadb,djci->bjai", extract_mat(g, "vvvv", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("cajk,cibk->bjai", extract_mat(g, "vvoo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("cajk,bkci->bjai", extract_mat(g, "vvoo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("cbik,cjak->bjai", extract_mat(g, "vvoo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("cbik,akcj->bjai", extract_mat(g, "vvoo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("ikjl,akbl->bjai", extract_mat(g, "oooo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("ikjl,blak->bjai", extract_mat(g, "oooo", o, v), extract_mat(p2, "AIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("Bkk,Baibj->bjai", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.50000000  * fixed_einsum("Bkk,Bbjai->bjai", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bca,Bcibj->bjai", extract_mat(g_p, "VAvv", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bca,Bbjci->bjai", extract_mat(g_p, "VAvv", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bcb,Bcjai->bjai", extract_mat(g_p, "VAvv", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("Bcb,Baicj->bjai", extract_mat(g_p, "VAvv", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("Bik,Bakbj->bjai", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("Bik,Bbjak->bjai", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("Bjk,Baibk->bjai", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("Bjk,Bbkai->bjai", extract_mat(g_p, "VAoo", o, v), extract_mat(p2, "VIvovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("Bkc,aibj,Bck->bjai", extract_mat(g_p, "IVov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * extract_mat(p2, "AIvovo", o, v) * fixed_einsum("Bkc,Bck->", extract_mat(g_p, "IVov", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("ia,Bckbj,Bck->bjai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("ia,Bbjck,Bck->bjai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ib,Bckaj,Bck->bjai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ib,Bajck,Bck->bjai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ja,Bckbi,Bck->bjai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("ja,Bbick,Bck->bjai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("jb,Bckai,Bck->bjai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.50000000  * fixed_einsum("jb,Baick,Bck->bjai", extract_mat(g_p, "IAov", o, v), extract_mat(p2, "VIvovo", o, v), extract_mat(s, "VIvo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kajb,cldi,cldk->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kajb,cidl,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kbia,cldj,cldk->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kbia,cjdl,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("icjb,dkal,cldk->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("icjb,akdl,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("iajc,dkbl,cldk->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("iajc,bkdl,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kcia,dlbj,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kcia,bjdl,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kcjb,dlai,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kcjb,aidl,ckdl->bjai", extract_mat(L, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kalb,cidj,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kalb,cjdi,cldk->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kajc,dlbi,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kajc,dibl,cldk->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kajc,bldi,cldk->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kajc,bidl,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kbic,dlaj,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kbic,djal,cldk->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kbic,aldj,cldk->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("kbic,ajdl,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("icjd,akbl,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  +0.25000000  * fixed_einsum("icjd,bkal,cldk->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(t, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcla,dibj,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcla,bjdi,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kclb,djai,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kclb,aidj,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcid,albj,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcid,bjal,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcib,dlaj,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcib,ajdl,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcjd,aibl,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcjd,blai,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcja,dlbi,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");
E_bjai[:,:,:,:] = E_bjai[:,:,:,:] .+  -0.25000000  * fixed_einsum("kcja,bidl,ckdl->bjai", extract_mat(g, "ovov", o, v), extract_mat(p2, "AIvovo", o, v), extract_mat(u, "vovo", o, v), optimize="optimal");