E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjci,bjca->ai", c2_4d, extract_mat(g, "vovv", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("bjak,bjik->ai", c2_4d, extract_mat(g, "vooo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("ja,bkci,bkcj->ai", extract_mat(F, "ov", o, v, B), c2_4d, extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("ib,cjak,bkcj->ai", extract_mat(F, "ov", o, v, B), c2_4d, extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("bjci,Aca,Abj->ai", c2_4d, extract_mat(g_p, "IVvv", o, v, B), extract_mat(s, "VIvo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjak,Aik,Abj->ai", c2_4d, extract_mat(g_p, "IVoo", o, v, B), extract_mat(s, "VIvo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjci,ka,bjck->ai", c2_4d, extract_mat(g_p, "IIov", o, v, B), extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjak,ic,bjck->ai", c2_4d, extract_mat(g_p, "IIov", o, v, B), extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bcia,bjdk,cjdk->ai", extract_mat(L, "vvov", o, v, B), c2_4d, extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("jkia,bkcl,bjcl->ai", extract_mat(L, "ooov", o, v, B), c2_4d, extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("bjci,bdka,ckdj->ai", c2_4d, extract_mat(g, "vvov", o, v, B), extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("bjci,cdka,bjdk->ai", c2_4d, extract_mat(g, "vvov", o, v, B), extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjci,kjla,bkcl->ai", c2_4d, extract_mat(g, "ooov", o, v, B), extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("bjak,bcid,cjdk->ai", c2_4d, extract_mat(g, "vvov", o, v, B), extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjak,ljic,blck->ai", c2_4d, extract_mat(g, "ooov", o, v, B), extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjak,lkic,bjcl->ai", c2_4d, extract_mat(g, "ooov", o, v, B), extract_mat(t2, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjci,cakd,bjdk->ai", c2_4d, extract_mat(g, "vvov", o, v, B), extract_mat(u, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("bjak,lcik,bjcl->ai", c2_4d, extract_mat(g, "ovoo", o, v, B), extract_mat(u, "vovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  -2.00000000  * fixed_einsum("bjck,Aia,Abjck->ai", c2_4d, extract_mat(g_p, "IVov", o, v, B), extract_mat(s2, "VIvovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjci,Aka,Abjck->ai", c2_4d, extract_mat(g_p, "IVov", o, v, B), extract_mat(s2, "VIvovo", o, v, B), optimize="optimal");
E_ai[:,:] = E_ai[:,:] .+  +2.00000000  * fixed_einsum("bjak,Aic,Abjck->ai", c2_4d, extract_mat(g_p, "IVov", o, v, B), extract_mat(s2, "VIvovo", o, v, B), optimize="optimal");